### ISSUE TITLE
mvn clean package失败

### ISSUE THREAD

**Issue by wind-gh** [taosdata/kafka-connect-tdengine#32]
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.taosdata.kafka.connect.config.SchemalessValidatorTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.031 s - in com.taosdata.kafka.connect.config.SchemalessValidatorTest
[INFO] Running com.taosdata.kafka.connect.config.TimeZoneValidatorTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in com.taosdata.kafka.connect.config.TimeZoneValidatorTest
[INFO] Running com.taosdata.kafka.connect.util.VersionUtilsTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in com.taosdata.kafka.connect.util.VersionUtilsTest
[INFO] Running com.taosdata.kafka.connect.TDengineTaskTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.036 s <<< FAILURE! - in com.taosdata.kafka.connect.TDengineTaskTest
[ERROR] com.taosdata.kafka.connect.TDengineTaskTest  Time elapsed: 0.036 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/alibaba/fastjson/JSONObject
	at com.taosdata.kafka.connect.TDengineTaskTest.before(TDengineTaskTest.java:121)
Caused by: java.lang.ClassNotFoundException: com.alibaba.fastjson.JSONObject
	at com.taosdata.kafka.connect.TDengineTaskTest.before(TDengineTaskTest.java:121)

[INFO] Running com.taosdata.kafka.connect.sink.TDengineSinkConnectorTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.018 s - in com.taosdata.kafka.connect.sink.TDengineSinkConnectorTest
[INFO] Running com.taosdata.kafka.connect.source.TimeStampOffsetTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 s - in com.taosdata.kafka.connect.source.TimeStampOffsetTest
[INFO] Running com.taosdata.kafka.connect.source.SourceInsertTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.004 s <<< FAILURE! - in com.taosdata.kafka.connect.source.SourceInsertTest
[ERROR] prepareData  Time elapsed: 0.003 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/alibaba/fastjson/JSONObject
	at com.taosdata.kafka.connect.source.SourceInsertTest.createConnection(SourceInsertTest.java:27)
	at com.taosdata.kafka.connect.source.SourceInsertTest.prepareData(SourceInsertTest.java:21)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   TDengineTaskTest.before:121 » NoClassDefFound com/alibaba/fastjson/JSONObject
[ERROR]   SourceInsertTest.prepareData:21->createConnection:27 » NoClassDefFound com/ali...
[INFO] 
[ERROR] Tests run: 7, Failures: 0, Errors: 2, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.878 s
[INFO] Finished at: 2023-03-20T17:15:56+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project kafka-connect-tdengine: There are test failures.
[ERROR] 
[ERROR] Please refer to /data/usr/kafka/connect/kafka-connect-tdengine-3.0/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by wind-gh** [comment]
本地打包是成功，但放到服务器运行不会消费kafka消息，所以想在服务器编译一下，但是编译异常。请问下要如何解决？
